//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMS.Core.Logging.ServiceModel
{
	using System.Runtime.Serialization;
	using System;


	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
	[System.Runtime.Serialization.DataContractAttribute(Name = "Log", Namespace = "http://schemas.datacontract.org/2004/07/XMS.Core.LogCenter.Model")]
	[System.SerializableAttribute()]
	public partial class Log : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
	{

		[System.NonSerializedAttribute()]
		private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string AgentNameField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string AgentPlatformField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string AgentVersionField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string AppNameField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string AppVersionField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string CategoryField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string ExceptionField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private long IdField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string LevelField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private System.DateTime LogTimeField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string MachineField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string MessageField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string MobileDeviceIdField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string MobileDeviceManufacturerField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string MobileDeviceModelField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string RawUrlField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private string UserIPField;

		[System.Runtime.Serialization.OptionalFieldAttribute()]
		private int UserIdField;

		[global::System.ComponentModel.BrowsableAttribute(false)]
		public System.Runtime.Serialization.ExtensionDataObject ExtensionData
		{
			get
			{
				return this.extensionDataField;
			}
			set
			{
				this.extensionDataField = value;
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string AgentName
		{
			get
			{
				return this.AgentNameField;
			}
			set
			{
				if ((object.ReferenceEquals(this.AgentNameField, value) != true))
				{
					this.AgentNameField = value;
					this.RaisePropertyChanged("AgentName");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string AgentPlatform
		{
			get
			{
				return this.AgentPlatformField;
			}
			set
			{
				if ((object.ReferenceEquals(this.AgentPlatformField, value) != true))
				{
					this.AgentPlatformField = value;
					this.RaisePropertyChanged("AgentPlatform");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string AgentVersion
		{
			get
			{
				return this.AgentVersionField;
			}
			set
			{
				if ((object.ReferenceEquals(this.AgentVersionField, value) != true))
				{
					this.AgentVersionField = value;
					this.RaisePropertyChanged("AgentVersion");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string AppName
		{
			get
			{
				return this.AppNameField;
			}
			set
			{
				if ((object.ReferenceEquals(this.AppNameField, value) != true))
				{
					this.AppNameField = value;
					this.RaisePropertyChanged("AppName");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string AppVersion
		{
			get
			{
				return this.AppVersionField;
			}
			set
			{
				if ((object.ReferenceEquals(this.AppVersionField, value) != true))
				{
					this.AppVersionField = value;
					this.RaisePropertyChanged("AppVersion");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Category
		{
			get
			{
				return this.CategoryField;
			}
			set
			{
				if ((object.ReferenceEquals(this.CategoryField, value) != true))
				{
					this.CategoryField = value;
					this.RaisePropertyChanged("Category");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Exception
		{
			get
			{
				return this.ExceptionField;
			}
			set
			{
				if ((object.ReferenceEquals(this.ExceptionField, value) != true))
				{
					this.ExceptionField = value;
					this.RaisePropertyChanged("Exception");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public long Id
		{
			get
			{
				return this.IdField;
			}
			set
			{
				if ((this.IdField.Equals(value) != true))
				{
					this.IdField = value;
					this.RaisePropertyChanged("Id");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Level
		{
			get
			{
				return this.LevelField;
			}
			set
			{
				if ((object.ReferenceEquals(this.LevelField, value) != true))
				{
					this.LevelField = value;
					this.RaisePropertyChanged("Level");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public System.DateTime LogTime
		{
			get
			{
				return this.LogTimeField;
			}
			set
			{
				if ((this.LogTimeField.Equals(value) != true))
				{
					this.LogTimeField = value;
					this.RaisePropertyChanged("LogTime");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Machine
		{
			get
			{
				return this.MachineField;
			}
			set
			{
				if ((object.ReferenceEquals(this.MachineField, value) != true))
				{
					this.MachineField = value;
					this.RaisePropertyChanged("Machine");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string Message
		{
			get
			{
				return this.MessageField;
			}
			set
			{
				if ((object.ReferenceEquals(this.MessageField, value) != true))
				{
					this.MessageField = value;
					this.RaisePropertyChanged("Message");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string MobileDeviceId
		{
			get
			{
				return this.MobileDeviceIdField;
			}
			set
			{
				if ((object.ReferenceEquals(this.MobileDeviceIdField, value) != true))
				{
					this.MobileDeviceIdField = value;
					this.RaisePropertyChanged("MobileDeviceId");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string MobileDeviceManufacturer
		{
			get
			{
				return this.MobileDeviceManufacturerField;
			}
			set
			{
				if ((object.ReferenceEquals(this.MobileDeviceManufacturerField, value) != true))
				{
					this.MobileDeviceManufacturerField = value;
					this.RaisePropertyChanged("MobileDeviceManufacturer");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string MobileDeviceModel
		{
			get
			{
				return this.MobileDeviceModelField;
			}
			set
			{
				if ((object.ReferenceEquals(this.MobileDeviceModelField, value) != true))
				{
					this.MobileDeviceModelField = value;
					this.RaisePropertyChanged("MobileDeviceModel");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string RawUrl
		{
			get
			{
				return this.RawUrlField;
			}
			set
			{
				if ((object.ReferenceEquals(this.RawUrlField, value) != true))
				{
					this.RawUrlField = value;
					this.RaisePropertyChanged("RawUrl");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public string UserIP
		{
			get
			{
				return this.UserIPField;
			}
			set
			{
				if ((object.ReferenceEquals(this.UserIPField, value) != true))
				{
					this.UserIPField = value;
					this.RaisePropertyChanged("UserIP");
				}
			}
		}

		[System.Runtime.Serialization.DataMemberAttribute()]
		public int UserId
		{
			get
			{
				return this.UserIdField;
			}
			set
			{
				if ((this.UserIdField.Equals(value) != true))
				{
					this.UserIdField = value;
					this.RaisePropertyChanged("UserId");
				}
			}
		}

		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected void RaisePropertyChanged(string propertyName)
		{
			System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
			if ((propertyChanged != null))
			{
				propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
	[System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.xiaomishu.com/logCenter", ConfigurationName = "XMS.Core.Logging.ServiceModel.ILogCenterService")]
	public interface ILogCenterService
	{
		[System.ServiceModel.OperationContractAttribute(Action = "http://www.xiaomishu.com/logCenter/ILogCenterService/AddLog", ReplyAction = "http://www.xiaomishu.com/logCenter/ILogCenterService/AddLogResponse")]
		XMS.Core.ReturnValue<long> AddLog(XMS.Core.Logging.ServiceModel.Log log);
	}
}
