//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMS.Core.Members {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Member", Namespace="http://schemas.datacontract.org/2004/07/XMS.Core.SSO.Model")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(XMS.Core.Members.MemberEx))]
    public partial class Member : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsLockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMPVerifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsValidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastLoginTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastUpdateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoginCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoginFailCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private XMS.Core.Members.Sex SexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActivated {
            get {
                return this.IsActivatedField;
            }
            set {
                if ((this.IsActivatedField.Equals(value) != true)) {
                    this.IsActivatedField = value;
                    this.RaisePropertyChanged("IsActivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsLocked {
            get {
                return this.IsLockedField;
            }
            set {
                if ((this.IsLockedField.Equals(value) != true)) {
                    this.IsLockedField = value;
                    this.RaisePropertyChanged("IsLocked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMPVerified {
            get {
                return this.IsMPVerifiedField;
            }
            set {
                if ((this.IsMPVerifiedField.Equals(value) != true)) {
                    this.IsMPVerifiedField = value;
                    this.RaisePropertyChanged("IsMPVerified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid {
            get {
                return this.IsValidField;
            }
            set {
                if ((this.IsValidField.Equals(value) != true)) {
                    this.IsValidField = value;
                    this.RaisePropertyChanged("IsValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastLoginTime {
            get {
                return this.LastLoginTimeField;
            }
            set {
                if ((this.LastLoginTimeField.Equals(value) != true)) {
                    this.LastLoginTimeField = value;
                    this.RaisePropertyChanged("LastLoginTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastUpdateTime {
            get {
                return this.LastUpdateTimeField;
            }
            set {
                if ((this.LastUpdateTimeField.Equals(value) != true)) {
                    this.LastUpdateTimeField = value;
                    this.RaisePropertyChanged("LastUpdateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoginCount {
            get {
                return this.LoginCountField;
            }
            set {
                if ((this.LoginCountField.Equals(value) != true)) {
                    this.LoginCountField = value;
                    this.RaisePropertyChanged("LoginCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoginFailCount {
            get {
                return this.LoginFailCountField;
            }
            set {
                if ((this.LoginFailCountField.Equals(value) != true)) {
                    this.LoginFailCountField = value;
                    this.RaisePropertyChanged("LoginFailCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhone {
            get {
                return this.MobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneField, value) != true)) {
                    this.MobilePhoneField = value;
                    this.RaisePropertyChanged("MobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public XMS.Core.Members.Sex Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
		//protected void RaisePropertyChanged(string propertyName) {
		//    System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
		//    if ((propertyChanged != null)) {
		//        propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		//    }
		//}
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MemberEx", Namespace="http://schemas.datacontract.org/2004/07/XMS.Core.SSO.Model")]
    [System.SerializableAttribute()]
    public partial class MemberEx : XMS.Core.Members.Member {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sex", Namespace="http://schemas.datacontract.org/2004/07/XMS.Core.SSO.Model")]
    public enum Sex : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknow = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.57.cn/Member", ConfigurationName="IMemberService")]
    public interface IMemberService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.57.cn/Member/IMemberService/Lock", ReplyAction="http://www.57.cn/Member/IMemberService/LockResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.Member>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.MemberEx>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.Member[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.MemberEx[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<int>))]
        XMS.Core.ReturnValue Lock(int memberId, int operatorId, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.57.cn/Member/IMemberService/Unlock", ReplyAction="http://www.57.cn/Member/IMemberService/UnlockResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.Member>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.MemberEx>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.Member[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.MemberEx[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<int>))]
        XMS.Core.ReturnValue Unlock(int memberId, int operatorId, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.57.cn/Member/IMemberService/Disable", ReplyAction="http://www.57.cn/Member/IMemberService/DisableResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.Member>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.MemberEx>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.Member[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.MemberEx[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<int>))]
        XMS.Core.ReturnValue Disable(int memberId, int operatorId, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.57.cn/Member/IMemberService/Enable", ReplyAction="http://www.57.cn/Member/IMemberService/EnableResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.Member>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.MemberEx>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.Member[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.MemberEx[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<int>))]
        XMS.Core.ReturnValue Enable(int memberId, int operatorId, string reason);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.57.cn/Member/IMemberService/GetMemberById", ReplyAction="http://www.57.cn/Member/IMemberService/GetMemberByIdResponse")]
        XMS.Core.ReturnValue<XMS.Core.Members.Member> GetMemberById(int memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.57.cn/Member/IMemberService/GetMemberExById", ReplyAction="http://www.57.cn/Member/IMemberService/GetMemberExByIdResponse")]
        XMS.Core.ReturnValue<XMS.Core.Members.MemberEx> GetMemberExById(int memberId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.57.cn/Member/IMemberService/GetMemberByEmailOrMobilePhone", ReplyAction="http://www.57.cn/Member/IMemberService/GetMemberByEmailOrMobilePhoneResponse")]
        XMS.Core.ReturnValue<XMS.Core.Members.Member> GetMemberByEmailOrMobilePhone(string emailOrMobilePhone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.57.cn/Member/IMemberService/GetMemberExByEmailOrMobilePhone", ReplyAction="http://www.57.cn/Member/IMemberService/GetMemberExByEmailOrMobilePhoneResponse")]
        XMS.Core.ReturnValue<XMS.Core.Members.MemberEx> GetMemberExByEmailOrMobilePhone(string emailOrMobilePhone);

		[System.ServiceModel.OperationContractAttribute(Action = "http://www.57.cn/Member/IMemberService/GetMemberByNickName", ReplyAction = "http://www.57.cn/Member/IMemberService/GetMemberByNickNamePhoneResponse")]
		XMS.Core.ReturnValue<XMS.Core.Members.Member> GetMemberByNickName(string nickName);

		[System.ServiceModel.OperationContractAttribute(Action = "http://www.57.cn/Member/IMemberService/GetMemberExByNickName", ReplyAction = "http://www.57.cn/Member/IMemberService/GetMemberExByNickNamePhoneResponse")]
		XMS.Core.ReturnValue<XMS.Core.Members.MemberEx> GetMemberExByNickName(string nickName);
       
        [System.ServiceModel.OperationContractAttribute(Action="http://www.57.cn/Member/IMemberService/GetMemberByIds", ReplyAction="http://www.57.cn/Member/IMemberService/GetMemberByIdsResponse")]
        XMS.Core.ReturnValue<XMS.Core.Members.Member[]> GetMemberByIds(int[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.57.cn/Member/IMemberService/GetMemberExByIds", ReplyAction="http://www.57.cn/Member/IMemberService/GetMemberExByIdsResponse")]
        XMS.Core.ReturnValue<XMS.Core.Members.MemberEx[]> GetMemberExByIds(int[] memberIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.57.cn/Member/IMemberService/AddMember", ReplyAction="http://www.57.cn/Member/IMemberService/AddMemberResponse")]
        XMS.Core.ReturnValue<int> AddMember(XMS.Core.Members.MemberEx member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.57.cn/Member/IMemberService/UpdateMember", ReplyAction="http://www.57.cn/Member/IMemberService/UpdateMemberResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.Member>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.MemberEx>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.Member[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.MemberEx[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<int>))]
        XMS.Core.ReturnValue UpdateMember(XMS.Core.Members.MemberEx member);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.57.cn/Member/IMemberService/ResetMemberPassword", ReplyAction="http://www.57.cn/Member/IMemberService/ResetMemberPasswordResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.Member>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.MemberEx>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.Member[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<XMS.Core.Members.MemberEx[]>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XMS.Core.ReturnValue<int>))]
        XMS.Core.ReturnValue ResetMemberPassword(int memberId, int operatorId, string reason, bool sendNewPasswordToMobilePhone, bool sendNewPasswordToEmail);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMemberServiceChannel : XMS.Core.Members.IMemberService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberServiceClient : System.ServiceModel.ClientBase<XMS.Core.Members.IMemberService>, XMS.Core.Members.IMemberService {
        
        public MemberServiceClient() {
        }
        
        public MemberServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public XMS.Core.ReturnValue Lock(int memberId, int operatorId, string reason) {
            return base.Channel.Lock(memberId, operatorId, reason);
        }
        
        public XMS.Core.ReturnValue Unlock(int memberId, int operatorId, string reason) {
            return base.Channel.Unlock(memberId, operatorId, reason);
        }
        
        public XMS.Core.ReturnValue Disable(int memberId, int operatorId, string reason) {
            return base.Channel.Disable(memberId, operatorId, reason);
        }
        
        public XMS.Core.ReturnValue Enable(int memberId, int operatorId, string reason) {
            return base.Channel.Enable(memberId, operatorId, reason);
        }
        
        public XMS.Core.ReturnValue<XMS.Core.Members.Member> GetMemberById(int memberId) {
            return base.Channel.GetMemberById(memberId);
        }
        
        public XMS.Core.ReturnValue<XMS.Core.Members.MemberEx> GetMemberExById(int memberId) {
            return base.Channel.GetMemberExById(memberId);
        }
        
        public XMS.Core.ReturnValue<XMS.Core.Members.Member> GetMemberByEmailOrMobilePhone(string emailOrMobilePhone) {
            return base.Channel.GetMemberByEmailOrMobilePhone(emailOrMobilePhone);
        }
        
        public XMS.Core.ReturnValue<XMS.Core.Members.MemberEx> GetMemberExByEmailOrMobilePhone(string emailOrMobilePhone) {
            return base.Channel.GetMemberExByEmailOrMobilePhone(emailOrMobilePhone);
        }

		public XMS.Core.ReturnValue<XMS.Core.Members.Member> GetMemberByNickName(string nickName)
		{
			return base.Channel.GetMemberByNickName(nickName);
		}

		public XMS.Core.ReturnValue<XMS.Core.Members.MemberEx> GetMemberExByNickName(string nickName)
		{
			return base.Channel.GetMemberExByNickName(nickName);
		}

		public XMS.Core.ReturnValue<XMS.Core.Members.Member[]> GetMemberByIds(int[] memberIds) {
            return base.Channel.GetMemberByIds(memberIds);
        }
        
        public XMS.Core.ReturnValue<XMS.Core.Members.MemberEx[]> GetMemberExByIds(int[] memberIds) {
            return base.Channel.GetMemberExByIds(memberIds);
        }
        
        public XMS.Core.ReturnValue<int> AddMember(XMS.Core.Members.MemberEx member) {
            return base.Channel.AddMember(member);
        }
        
        public XMS.Core.ReturnValue UpdateMember(XMS.Core.Members.MemberEx member) {
            return base.Channel.UpdateMember(member);
        }
        
        public XMS.Core.ReturnValue ResetMemberPassword(int memberId, int operatorId, string reason, bool sendNewPasswordToMobilePhone, bool sendNewPasswordToEmail) {
            return base.Channel.ResetMemberPassword(memberId, operatorId, reason, sendNewPasswordToMobilePhone, sendNewPasswordToEmail);
        }
    }
}
